import Navbar from "@/components/Navbar"
import { NavBarLinks } from "@/types";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const headerNavLinks : NavBarLinks = {
  MesExperiences: "Mes Experiences",
  MesProjets: "Mes Projets",
  MonProfil: "MonProfil"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar links = {headerNavLinks}/> 
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
